
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template

 */
package principal;

import javax.swing.*;
import principal.frmlogin;
import java.util.List;
import java.util.ArrayList;
import java.awt.*;
import java.awt.event.*;

/**
 *
 * @author NeyBg
 */
public class frmroles extends javax.swing.JFrame {
    private String rolUsuario;
    private JPanel panelNotificaciones;
    private JTextArea areaNotificaciones;
    private boolean notificacionesVisible = false;


    /**
     * Creates new form frmroles
     */
    
    public frmroles(String rol) {
        this.rolUsuario = rol;
        initComponents();
        initPanelNotificaciones();
        configurarPermisosBasicos();
        setTitle("Sistema de Prestamos - Rol: " + rol); // Muestra el Rol en el titulo
        setLocationRelativeTo(null); //centrar ventana
    }
    
    private void configurarPermisosBasicos(){ 
        //Deshabilitar todo primero
        botonReservaSala.setEnabled(false);
        botonPrestamoEquipo.setEnabled(false);
        botonHistorial.setEnabled(false);

        //configurar segun el rol.
        if (rolUsuario.equalsIgnoreCase("estudiante")){
            botonPrestamoEquipo.setEnabled(true);
            botonHistorial.setEnabled(true);
            botonReservaSala.setToolTipText("solo para profesores y administrativos pueden reservar salas");
             
        }
        else if(rolUsuario.equalsIgnoreCase("profesor")|| rolUsuario.equalsIgnoreCase("administrativo")){
            botonReservaSala.setEnabled(true);
            botonPrestamoEquipo.setEnabled(true);
            botonHistorial.setEnabled(true); // que vean su historial
        }
        else if (rolUsuario.equalsIgnoreCase("administrador")) {
            botonReservaSala.setEnabled(true);
            botonPrestamoEquipo.setEnabled(true);
            botonHistorial.setEnabled(true);
        }
        // Configurar acciones básicas
        botonSalir.addActionListener(e -> {
            new frmlogin().setVisible(true);
            this.dispose();
        });
        botonReservaSala.addActionListener(e -> {
            if (!rolUsuario.equalsIgnoreCase("estudiante")) {
                JOptionPane.showMessageDialog(this, "Aquí abrirías el formulario de reserva de salas");
            } else {
                JOptionPane.showMessageDialog(this, 
                    "Los estudiantes no pueden reservar salas", 
                    "Acceso denegado", 
                    JOptionPane.WARNING_MESSAGE);
            }
        });
        
        System.out.println("Rol actual: " + rolUsuario + 
                " | Prestamo: " + botonPrestamoEquipo.isEnabled() +
                " | Sala: " + botonReservaSala.isEnabled());
    }
            
            
            
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonReservaSala = new javax.swing.JButton();
        botonPrestamoEquipo = new javax.swing.JButton();
        botonNotificacion = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        botonHistorial = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/udi.png"))); // NOI18N

        botonReservaSala.setBackground(new java.awt.Color(0, 102, 153));
        botonReservaSala.setForeground(new java.awt.Color(255, 255, 255));
        botonReservaSala.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sala-de-conferencias (1).png"))); // NOI18N
        botonReservaSala.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reservar Sala", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        botonReservaSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReservaSalaActionPerformed(evt);
            }
        });

        botonPrestamoEquipo.setBackground(new java.awt.Color(0, 102, 153));
        botonPrestamoEquipo.setForeground(new java.awt.Color(255, 255, 255));
        botonPrestamoEquipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/equipo.png"))); // NOI18N
        botonPrestamoEquipo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Prestamo Equipo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        botonPrestamoEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPrestamoEquipoActionPerformed(evt);
            }
        });

        botonNotificacion.setForeground(new java.awt.Color(0, 102, 153));
        botonNotificacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/campana.png"))); // NOI18N
        botonNotificacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Notificaciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 102, 153))); // NOI18N
        botonNotificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNotificacionActionPerformed(evt);
            }
        });

        botonSalir.setBackground(new java.awt.Color(0, 102, 153));
        botonSalir.setForeground(new java.awt.Color(255, 255, 255));
        botonSalir.setText("Salir");

        botonHistorial.setBackground(new java.awt.Color(0, 102, 153));
        botonHistorial.setForeground(new java.awt.Color(255, 255, 255));
        botonHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/historial-de-transacciones.png"))); // NOI18N
        botonHistorial.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Historial", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonSalir))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonPrestamoEquipo)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(botonReservaSala)
                        .addGap(18, 18, 18)
                        .addComponent(botonHistorial)
                        .addContainerGap(75, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonNotificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonSalir))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonReservaSala)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(botonNotificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(121, 121, 121)
                                        .addComponent(botonHistorial))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botonPrestamoEquipo)))))
                        .addGap(0, 151, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonPrestamoEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPrestamoEquipoActionPerformed
            // TODO add your handling code here:
        botonPrestamoEquipo.addActionListener(e -> {
            new frmequipo().setVisible(true);
            this.dispose(); //cierra la venta actual
        });
    }//GEN-LAST:event_botonPrestamoEquipoActionPerformed

    private void botonReservaSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReservaSalaActionPerformed
        // TODO add your handling code here:
        botonReservaSala.addActionListener(e -> {
            if (!rolUsuario.equalsIgnoreCase("estudiante")) {
                new frmsala(rolUsuario).setVisible(true);
                this.dispose();
            }
        });
    }//GEN-LAST:event_botonReservaSalaActionPerformed

    // En el constructor o initComponents():
private void initPanelNotificaciones() {
    panelNotificaciones = new JPanel();
    panelNotificaciones.setLayout(new BorderLayout());
    panelNotificaciones.setBorder(BorderFactory.createTitledBorder("Notificaciones"));
    
    areaNotificaciones = new JTextArea(5, 30);
    areaNotificaciones.setEditable(false);
    panelNotificaciones.add(new JScrollPane(areaNotificaciones), BorderLayout.CENTER);
    panelNotificaciones.setVisible(false);
    
    // Agregar al panel principal (ajusta según tu layout)
    jPanel1.add(panelNotificaciones, BorderLayout.SOUTH);
}
    
    private void botonNotificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNotificacionActionPerformed
        // TODO add your handling code here:
        // Ejemplo con datos simulados
        List<String> notificaciones = obtenerNotificacionesUsuario();
        StringBuilder texto = new StringBuilder();
    
    for (String notif : notificaciones) {
        texto.append("• ").append(notif).append("\n");
    }
    
    areaNotificaciones.setText(texto.toString());
}

    private List<String> obtenerNotificacionesUsuario() {
    // Simulación - luego puedes conectar a tu base de datos
        List<String> notifs = new ArrayList<>();
        notifs.add("Préstamo de proyector aprobado (15/Nov)");
        notifs.add("Recordatorio: Sala 302 reservada para mañana");
        notifs.add("Nuevo equipo disponible: Cámara Sony 4K");
        return notifs;
    }//GEN-LAST:event_botonNotificacionActionPerformed

    /**
     * @param args the command line arguments
     */

     
    public static void main(String args[]) {


        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmroles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmroles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmroles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmroles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmroles("estudiante").setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonHistorial;
    private javax.swing.JButton botonNotificacion;
    private javax.swing.JButton botonPrestamoEquipo;
    private javax.swing.JButton botonReservaSala;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}










