
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package principal;
import principal.pruebas.conexion;
import java.util.ArrayList;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JFrame;

/**
 *
 * @author NeyBg
 */
public class frmregistro extends javax.swing.JFrame {
        

    /**
     * Creates new form frmregistro
     */

public class ConexionOracle {
    public static Connection getConexion() {

        Connection conn = null;
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            conn = DriverManager.getConnection(
                "jdbc:oracle:thin:@localhost:1521:xe", // Cambia tu cadena si es diferente
                "usuario", // tu usuario de Oracle
                "contrasena" // tu contraseña de Oracle
            );
        } catch (ClassNotFoundException | SQLException ex) {
            ex.printStackTrace();
        }
        return conn;
    }
}
    
public class BaseDatosTemporal {
    public static ArrayList<Usuario> usuarios = new ArrayList<>();
}

public class Usuario {
        private String nombre;
        private String apellido;
        private String correo;
        private String contrasena;
        private String rol;
        
        public Usuario(String nombre, String apellido, String correo, String contraseña, String rol) {
            this.nombre = nombre;
            this.apellido = apellido;
            this.correo = correo;
            this.contrasena = contraseña;
            this.rol = rol;
    }

    public String getCorreo() {
        return correo;
    }

    public String getContraseña() {
        return contrasena;
    }

    // Agrega más getters/setters si necesitas
}

    public frmregistro() {
        initComponents();

        
        
    }

    /**
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtequipos = new javax.swing.JLabel();
        fondoregistro = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtnombre = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtapellido = new javax.swing.JTextField();
        txtcontraseña = new javax.swing.JPasswordField();
        comboRol = new javax.swing.JComboBox<>();
        botregistrarusuario = new javax.swing.JButton();
        logoudi = new javax.swing.JLabel();
        txtequipos1 = new javax.swing.JLabel();

        txtequipos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtequipos.setForeground(new java.awt.Color(255, 255, 255));
        txtequipos.setText("LOGIN");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REGISTRO DE USUARIO");

        fondoregistro.setBackground(new java.awt.Color(0, 102, 153));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " REGISTRO & ROL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        txtnombre.setBackground(new java.awt.Color(0, 102, 153));
        txtnombre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        txtemail.setBackground(new java.awt.Color(0, 102, 153));
        txtemail.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Correo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        txtapellido.setBackground(new java.awt.Color(0, 102, 153));
        txtapellido.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Apellido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        txtcontraseña.setBackground(new java.awt.Color(0, 102, 153));
        txtcontraseña.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contraseña", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        comboRol.setBackground(new java.awt.Color(0, 102, 153));
        comboRol.setForeground(new java.awt.Color(255, 255, 255));
        comboRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estudiante", "Administrativo", "Profesor", "Administrador" }));
        comboRol.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo de Rol", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        comboRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRolActionPerformed(evt);
            }
        });

        botregistrarusuario.setForeground(new java.awt.Color(0, 102, 153));
        botregistrarusuario.setText("Registrar de Usuario");
        botregistrarusuario.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        botregistrarusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botregistrarusuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(comboRol, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtapellido, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                    .addComponent(txtcontraseña))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botregistrarusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtemail)
                    .addComponent(txtcontraseña))
                .addGap(18, 18, 18)
                .addComponent(comboRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botregistrarusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        logoudi.setBackground(new java.awt.Color(0, 102, 153));
        logoudi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/udi.png"))); // NOI18N

        txtequipos1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtequipos1.setForeground(new java.awt.Color(255, 255, 255));
        txtequipos1.setText("REGISTRO");

        javax.swing.GroupLayout fondoregistroLayout = new javax.swing.GroupLayout(fondoregistro);
        fondoregistro.setLayout(fondoregistroLayout);
        fondoregistroLayout.setHorizontalGroup(
            fondoregistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoregistroLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(fondoregistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(fondoregistroLayout.createSequentialGroup()
                        .addComponent(logoudi, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtequipos1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoregistroLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );
        fondoregistroLayout.setVerticalGroup(
            fondoregistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoregistroLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(fondoregistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logoudi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtequipos1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoregistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoregistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRolActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_comboRolActionPerformed

    private void botregistrarusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botregistrarusuarioActionPerformed

// Obtener y limpiar los valores ingresados por el usuario desde los campos del formulario
        String nombre = txtnombre.getText().trim();
        String apellido = txtapellido.getText().trim();
        String correo = txtemail.getText().trim();
        String contrasena = new String(txtcontraseña.getPassword());
        String rol = (String) comboRol.getSelectedItem();

// Validación: asegurarse de que ningún campo esté vacío
        if (nombre.isEmpty() || apellido.isEmpty() || correo.isEmpty() || contrasena.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Nombre y apellido son obligatoris");
        return; // Sale del método si falta información
        }

        try {
    // Obtener conexión a la base de datos Oracle usando la clase ConexionOracle
            Connection con = conexion.getConnection();

            if (con != null) {
            // Verificación previa: comprobar si el correo ya está registrado en la base de datos
            String queryCheck = "SELECT COUNT(*) FROM USUARIO WHERE correo = ?";
            PreparedStatement pstCheck = con.prepareStatement(queryCheck);
            pstCheck.setString(1, correo);
            ResultSet rs = pstCheck.executeQuery();
            rs.next(); // Mover el cursor a la primera fila

        // Si ya existe un usuario con ese correo, mostrar mensaje y salir
                if (rs.getInt(1) > 0) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Ya existe un usuario con ese correo.");
                return;
                }

                if (apellido.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "El apellido es obligatorio");
                return;
                }    
                
        // Sentencia SQL para insertar un nuevo usuario en la tabla
                String queryInsert = "INSERT INTO USUARIO (ID_USUARIO, NOMBRE, APELLIDO, CORREO, ROL, CONTRASENA) VALUES (USUARIO_SEQ.NEXTVAL, ?, ?, ?, ?, ?)";
                PreparedStatement pst = con.prepareStatement(queryInsert);
                pst.setString(1, nombre);      //NOMBRE (solo nombre)
                pst.setString(2, apellido);    //APELLIDO (nuevo campo)
                pst.setString(3, correo);      //Correo
                pst.setString(4, rol);         //Rol
                pst.setString(5, contrasena);  //CONTRASENA

        // Ejecutar la inserción y verificar si se afectó alguna fila
                int filas = pst.executeUpdate();
                if (filas > 0) {
                // Si la inserción fue exitosa, mostrar mensaje y redirigir al login
                    javax.swing.JOptionPane.showMessageDialog(this, "Usuario registrado correctamente.");
                    frmlogin login = new frmlogin();
                    login.setVisible(true);
                    this.dispose(); // Cerrar el formulario actual
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Error al registrar usuario.");
                }

                // Cerrar recursos
                pst.close();
                con.close();
                } else {
                // Si la conexión es nula, notificar al usuario
                javax.swing.JOptionPane.showMessageDialog(this, "No se pudo conectar a la base de datos.");
                }
        } catch (Exception e) {
    // Captura y muestra cualquier error inesperado durante el proceso
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }


    }//GEN-LAST:event_botregistrarusuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmregistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmregistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmregistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmregistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmregistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botregistrarusuario;
    private javax.swing.JComboBox<String> comboRol;
    private javax.swing.JPanel fondoregistro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoudi;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JPasswordField txtcontraseña;
    private javax.swing.JTextField txtemail;
    private javax.swing.JLabel txtequipos;
    private javax.swing.JLabel txtequipos1;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}




 











