/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package principal;

/**
 *
 * @author NeyBg
 */
public class frmsala extends javax.swing.JFrame {
    private String rolUsuario; // Variable para almacenar el rol

        // Constructor modificado
    public frmsala(String rolUsuario) {
        this.rolUsuario = rolUsuario; // Guardamos el rol
        initComponents();
        setLocationRelativeTo(null); // Centrar ventana
    }
    

    /**
     * Creates new form frmsala
     */
    public frmsala() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtequipos1 = new javax.swing.JLabel();
        botonsala1 = new javax.swing.JButton();
        botonsala2 = new javax.swing.JButton();
        botonsala3 = new javax.swing.JButton();
        botonsala4 = new javax.swing.JButton();
        botonsala5 = new javax.swing.JButton();
        botonatras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SALAS");

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/udi.png"))); // NOI18N

        txtequipos1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtequipos1.setForeground(new java.awt.Color(255, 255, 255));
        txtequipos1.setText("SALAS");

        botonsala1.setBackground(new java.awt.Color(0, 102, 153));
        botonsala1.setForeground(new java.awt.Color(255, 255, 255));
        botonsala1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sala-de-control0.png"))); // NOI18N
        botonsala1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SALA_UNO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        botonsala2.setBackground(new java.awt.Color(0, 102, 153));
        botonsala2.setForeground(new java.awt.Color(255, 255, 255));
        botonsala2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sala-de-control1.png"))); // NOI18N
        botonsala2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SALA_DOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        botonsala3.setBackground(new java.awt.Color(0, 102, 153));
        botonsala3.setForeground(new java.awt.Color(255, 255, 255));
        botonsala3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sala-de-control2.png"))); // NOI18N
        botonsala3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SALA_TRES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        botonsala4.setBackground(new java.awt.Color(0, 102, 153));
        botonsala4.setForeground(new java.awt.Color(255, 255, 255));
        botonsala4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/saladecontrol3.png"))); // NOI18N
        botonsala4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SALA_CUATRO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        botonsala5.setBackground(new java.awt.Color(0, 102, 153));
        botonsala5.setForeground(new java.awt.Color(255, 255, 255));
        botonsala5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sala-de-control4.png"))); // NOI18N
        botonsala5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SALA_CINCO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        botonatras.setBackground(new java.awt.Color(0, 102, 153));
        botonatras.setForeground(new java.awt.Color(255, 255, 255));
        botonatras.setText("Atras");
        botonatras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonatrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtequipos1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonatras)
                        .addGap(39, 39, 39))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonsala2)
                        .addGap(18, 18, 18)
                        .addComponent(botonsala4)
                        .addGap(18, 18, 18)
                        .addComponent(botonsala5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(botonsala1)
                        .addGap(42, 42, 42)
                        .addComponent(botonsala3)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonatras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtequipos1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonsala1)
                    .addComponent(botonsala3))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonsala4)
                    .addComponent(botonsala5)
                    .addComponent(botonsala2))
                .addGap(0, 172, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonatrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonatrasActionPerformed
        // TODO add your handling code here:
    botonatras.addActionListener(e -> {
        new frmroles(rolUsuario).setVisible(true); // Pasa el rol nuevamente
        this.dispose();
    });    
    }//GEN-LAST:event_botonatrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmsala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmsala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmsala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmsala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmsala().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonatras;
    private javax.swing.JButton botonsala1;
    private javax.swing.JButton botonsala2;
    private javax.swing.JButton botonsala3;
    private javax.swing.JButton botonsala4;
    private javax.swing.JButton botonsala5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtequipos1;
    // End of variables declaration//GEN-END:variables
}
